volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:
  postgres:
      build:
          context: ./relational-data
          dockerfile: ./Dockerfile.dev
      volumes:
          - postgres-data:/var/lib/postgresql/data
      environment:
          - POSTGRES_MULTIPLE_DATABASES=monoservice,teams
          - POSTGRES_PASSWORD=test-databases
      ports:
          - 15432:5432
  teams:
    build:
      context: teams_api
      dockerfile: Dockerfile.dev
    ports:
      - 8100:8000
    volumes:
      - ./teams_api:/app
    depends on:
      - postgres
    environment:
      DATABASE_URL: postgresql://teams:password@postgres/teams
      WAIT_HOSTS: postgres:5432
      PGDATABASE: teams
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: table@table.com
      PGADMIN_DEFAULT_PASSWORD: table
      PGADMIN_DISABLE_POSTFIX: 1
  monoservice:
    build:
      context: monoservice
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./monoservice:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://monoservice:password@postgres/monoservice
      WAIT_HOSTS: postgres:5432
      PGDATABASE: monoservice
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API_HOST: http://localhost:8000
